source 'https://rubygems.org'

# fixing the ruby version
ruby '2.2.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
gem 'rake'

gem 'sidekiq'

# gem for versioning
gem 'paper_trail'

# action mailer for sending the emails
gem 'actionmailer'
# Use ActiveModel has_secure_password
gem 'bcrypt'
# devise for authentication
gem 'devise'
# cancan for authorization
gem 'cancancan'
# Use pg as the database for Active Record
gem 'pg'
# for json response https://github.com/rails-api/active_model_serializers
gem "active_model_serializers"

# use axlsx_rails for downloading excel
gem 'axlsx_rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use thin as the app server
gem 'thin'
gem 'nokogiri'
gem 'oauth'
gem 'omniauth'
gem 'omniauth-linkedin'


# this group cannot be named assets because that name creates problem
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'client_side_validations', :git => 'https://github.com/DavyJonesLocker/client_side_validations.git'
# Use twitter bootstrap
gem 'twitter-bootstrap-rails'
gem 'bootstrap-datepicker-rails'
# Use SCSS for stylesheets
gem 'sass-rails'
# using font awesome for icons
gem 'font-awesome-rails'
# bootstrap for base css
gem 'bootstrap-sass'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby
#for pagination
gem 'will_paginate','3.0.6'
#for pagination bootstrap clas
gem 'will_paginate-bootstrap'
gem 'best_in_place', '3.0.3'
# for giving writing option in dropdown
gem 'chosen-rails'
gem 'paperclip', '4.2.1'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'htmltoword', :git => 'https://github.com/nickfrandsen/htmltoword.git'

# for enabling AJAX file uploads
gem 'remotipart', '~> 1.2'
group :development, :test do
	# mini profiler for testing speed of the process
	gem 'rack-mini-profiler'
	# for annotating model for its properties automatically
	gem 'annotate'
	# byebug for command line debugging
	gem 'byebug'
	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'
	# rspec for testing
	gem "rspec-rails"
	# factory_girl for model mocks
	gem "factory_girl_rails"
	# for additional matchers in the specs
	gem 'shoulda-matchers'
	# faker for random data
	gem 'faker'
	gem 'metric_fu'
end

group :doc do
	# bundle exec rake doc:rails generates the API under doc/api.
	gem 'sdoc', :require => false
end

group :deployment do
	# Use Capistrano for deployment including rails specific capistrano functions
	gem 'capistrano-rails'
end

group :test do
	gem 'capybara'
	gem 'cucumber'
	gem 'rspec'
	gem 'cucumber-rails',:require => false
	# database_cleaner is not required, but highly recommended
	gem 'database_cleaner'
	gem 'headless'
	gem 'selenium-webdriver'
end
